[package]
name = "my_actor_project"
version = "0.1.0"
edition = "2021"

[dependencies]
actor_system = { path = "../actor_system" }
log = "0.4"
env_logger = "0.10"
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"
rand = "0.8"